### ISSUE TITLE
Failed to resolve com.github.diogobernardino:CircularCounter:5a6a405282

### ISSUE THREAD

**Issue by elabedkhaled** [diogobernardino/CircularCounter#1]
i have this code in my gradle 
repositories {
    maven {
        url "https://jitpack.io"
    }
}
dependencies {
    compile('com.github.diogobernardino:CircularCounter:5a6a405282') {
        exclude group: 'com.android.support', module: 'support-v4'
    }

```
repositories {
    mavenCentral()
}
dependencies {
    compile 'me.leolin:ShortcutBadger:1.1.3@aar'
}
```

}
 but i have the error "faied to resolve com.github.diogobernardino:CircularCounter:5a6a405282" ??

**Comment by diogobernardino** [comment]
That's because the library isn't neither in jitpack, maven or any other repo.

**Comment by elabedkhaled** [comment]
please how can i download it from any where else  ? i really need it . thank you

**Comment by diogobernardino** [comment]
In Github, there is a "Download Zip" button in every repository page. Give it a try.
